# Simple workflow for deploying static content to GitHub Pages
name: 02 copy files to another Repo


on:
  # Runs on pushes targeting the default branch
  # push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  file-sync:
    name: File Sync
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Test Action
        uses: ./dist
        with:
          DRY_RUN: true
          FILE_PATTERNS: |
            ^README.md$
            ^.github/workflows/sync-.*
          TARGET_REPOS: |
            theangkko/BRSTEAM-OfficeAddin
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            "@semantic-release/commit-analyzer"
            "@semantic-release/release-notes-generator"
            "@semantic-release/git
            "@semantic-release/github
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          
          
