# Simple workflow for deploying static content to GitHub Pages
name: 02 copy files to another Repo


on:
  # Runs on pushes targeting the default branch
  # push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  copy-file_READMEmd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUBLISH_TOKEN }}
      with:
        source_file: 'README.md'
        destination_repo: 'theangkko/BRSTEAM-OfficeAddin'
        destination_folder: './'
        user_email: 'theangkko@gmail.com.com'
        user_name: 'theangkko'
        commit_message: 'A custom message for the commit'
          
          
  file-sync:
    name: File Sync
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Test Action
        uses: ./dist
        with:
          DRY_RUN: true
          FILE_PATTERNS: |
            ^README.md$
            ^.github/workflows/sync-.*
          TARGET_REPOS: |
            theangkko/BRSTEAM-OfficeAddin
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            "@semantic-release/commit-analyzer"
            "@semantic-release/release-notes-generator"
            "@semantic-release/git
            "@semantic-release/github
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
